name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4
        with:
          cache-read-only: false

      - name: Build release MSI
        run: ./gradlew :composeApp:packageReleaseMsi --no-daemon
        shell: bash

      - name: Find MSI file
        id: find_msi
        run: |
          $msiFile = Get-ChildItem -Path "composeApp/build/compose/binaries/main-release/msi" -Filter "*.msi" -Recurse | Select-Object -First 1
          $msiPath = $msiFile.FullName
          echo "MSI_PATH=$msiPath" >> $env:GITHUB_OUTPUT
          Write-Host "Found MSI at: $msiPath"
        shell: pwsh

      - name: Upload MSI as Artifact
        uses: actions/upload-artifact@v4
        with:
          name: msi-installer-latest
          path: ${{ steps.find_msi.outputs.MSI_PATH }}
          retention-days: 7

  release:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Extract version from tag
        id: version
        run: |
          TAG_NAME=${GITHUB_REF#refs/tags/v}
          echo "VERSION=$TAG_NAME" >> $GITHUB_OUTPUT
          echo "Extracted version: $TAG_NAME"
        shell: bash

      - name: Download MSI Artifact
        uses: actions/download-artifact@v4
        with:
          name: msi-installer-latest
          path: ./artifacts

      - name: Create Release and Upload Assets
        uses: softprops/action-gh-release@v2
        with:
          name: Release ${{ steps.version.outputs.VERSION }}
          body: |
            Release version ${{ steps.version.outputs.VERSION }}

            ## Installation
            Download the MSI installer below and run it to install MeijoPharmCasherApp.

            ## Changes
            See commit history for details.
          files: ./artifacts/*.msi
          draft: false
          prerelease: false
