name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  build-and-release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4
        with:
          cache-read-only: false

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
        shell: bash

      - name: Build release MSI
        run: ./gradlew :composeApp:packageReleaseMsi --no-daemon
        shell: bash

      - name: Extract version from tag
        id: version
        run: |
          TAG_NAME=${GITHUB_REF#refs/tags/v}
          echo "VERSION=$TAG_NAME" >> $GITHUB_OUTPUT
          echo "Extracted version: $TAG_NAME"
        shell: bash

      - name: Find MSI file
        id: find_msi
        run: |
          MSI_PATH=$(find composeApp/build/compose/binaries/main-release/msi -name "*.msi" -type f | head -n 1)
          echo "MSI_PATH=$MSI_PATH" >> $GITHUB_OUTPUT
          echo "Found MSI: $MSI_PATH"
        shell: bash

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref_name }}
          release_name: Release ${{ steps.version.outputs.VERSION }}
          body: |
            Release version ${{ steps.version.outputs.VERSION }}

            ## Installation
            Download the MSI installer below and run it to install MeijoPharmCasherApp.

            ## Changes
            See commit history for details.
          draft: false
          prerelease: false

      - name: Upload MSI to Release
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ${{ steps.find_msi.outputs.MSI_PATH }}
          asset_name: MeijoPharmCasherApp-${{ steps.version.outputs.VERSION }}.msi
          asset_content_type: application/x-msi
